#!/usr/bin/python -u
#
# Project 2 Starter Code
#

import sys
import socket
import time
import datetime
import select
import json

MSG_SIZE = 1500
DATA_SIZE = 1000
TIMEOUT = 30
SEQUENCE = 0

# Bind to localhost and an ephemeral port
IP_PORT = sys.argv[1]
UDP_IP = IP_PORT[0:IP_PORT.find(":")]
UDP_PORT = int(IP_PORT[IP_PORT.find(":")+1:])
dest = (UDP_IP, UDP_PORT)

#Outbox for unacked messages
outbox = []

rtt = -1
synSentAt = 0

# Set up the socket
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
sock.settimeout(TIMEOUT)

def log(string):
  sys.stderr.write(datetime.datetime.now().strftime("%H:%M:%S.%f") + " " + string + "\n")


def send_syn():
    global synSentAt
    msg = json.dumps({"syn": True, "eof": False, "data": False})
    if sock.sendto(msg, dest) < len(msg):
        log("[error] unable to fully send packet")
    else:
        synSentAt = time.time()
        log("[syn sent]")

# Sends the given message to the given destination
def send_msg_to_dest(msg, dest):
  outbox.append(msg)
  msgJson = json.loads(msg)
  seqNum = msgJson['sequence']
  datalen = len(msgJson['data'])
  if sock.sendto(msg, dest) < len(msg):
    log("[error] unable to fully send packet")
  else:
    log("[send data] " + str(seqNum) + " (" + str(datalen) + ")")

def send_next_packet():
  global SEQUENCE

  data = sys.stdin.read(DATA_SIZE)
  if (len(data) > 0):
    msg = json.dumps({"sequence": SEQUENCE, "data": data, "ack": False, "eof": False, "syn": False})
    SEQUENCE += len(data)


    send_msg_to_dest(msg, dest)

    return True
  elif len(outbox) != 0:
    for message in outbox:
      send_msg_to_dest(message, dest)
    return True
  else:
    return False

# Send first packet
send_syn()

# Now read in data, send packets
while True:
  log("ABOUT TO SLEEP")
  result = sock.recvfrom(MSG_SIZE)

  if result:
    (data, addr) = result
    try:
      decoded = json.loads(data)

      if (decoded['syn']):
          rtt = (time.time() - synSentAt)
          send_next_packet()

      # The sequence number for the oldest message in the outbox
      oldestMessage = json.loads(outbox[0])
      outboxStartingSeqNum = oldestMessage['sequence']
      if decoded['ack'] == outboxStartingSeqNum:
        log("[recv ack] " + str(decoded['ack']))
        outbox.pop(0)
        TIMEOUT = 30

        # Try to send next packet; break if no more data
        if (not send_next_packet()):
          break

      # If there is an ack with a different sequence number
      elif (decoded['ack']):
          log("[recv ack] " + str(decoded['ack']))

          for message in outbox:
          send_msg_to_dest(message, dest)


    except (ValueError, KeyError, TypeError):
      log("[recv corrupt packet]")
  else:
    log("[error] timeout")
    TIMEOUT = TIMEOUT * 2
    for message in outbox:
      send_msg_to_dest(message, dest)


sock.sendto(json.dumps({"eof": True, "data": "", "sequence": SEQUENCE, "ack": False}), dest)
sys.exit(0)
